name:                interpreters
version:             0.1.0.0
github:              "maxwellpeterson/interpreters"
license:             MIT
author:              "Max Peterson"
copyright:           "2021 Max Peterson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxwellpeterson/interpreters#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
    - ExplicitForAll
    - ScopedTypeVariables

executables:
  interpreters-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interpreters

tests:
  interpreters-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interpreters
    - hspec
    - QuickCheck
